from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_AUTO_SIZE
import json
import uuid
import os # Import os for path checking

def create_ppt_from_json(json_string: str):
    try:
        data = json.loads(json_string)
    except json.JSONDecodeError:
        return None

    prs = Presentation()
    
    # --- Professional Design Elements ---
    background_color = RGBColor(12, 34, 56)
    default_font_color = RGBColor(255, 255, 255)
    title_font_size = Pt(30) # Slightly smaller title font
    body_font_size = Pt(14)  # Slightly smaller body font

    def set_slide_background(slide):
        slide.background.fill.solid()
        slide.background.fill.fore_color.rgb = background_color
        
    # --- Title Slide ---
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    title.text = data.get("presentation_title", "Presentation")
    title.text_frame.paragraphs[0].font.size = title_font_size
    title.text_frame.paragraphs[0].font.color.rgb = default_font_color
    
    if len(slide.placeholders) > 1:
        subtitle = slide.placeholders[1]
        subtitle.text = "Generated by Gemini"
        subtitle.text_frame.paragraphs[0].font.size = Pt(18) # Subtitle font size
        subtitle.text_frame.paragraphs[0].font.color.rgb = default_font_color
    
    set_slide_background(slide)

    # --- Content Slides ---
    for slide_data in data.get("slides", []):
        content_slide_layout = prs.slide_layouts[1] # Title and Content
        slide = prs.slides.add_slide(content_slide_layout)
        
        title = slide.shapes.title
        title.text = slide_data.get("title", "")
        title.text_frame.paragraphs[0].font.size = title_font_size
        title.text_frame.paragraphs[0].font.color.rgb = default_font_color

        # Find the content placeholder by type or index
        content_placeholder = None
        for shape in slide.placeholders:
            if shape.is_placeholder and shape.has_text_frame and shape.placeholder_format.idx == 1:
                content_placeholder = shape
                break
        
        if content_placeholder:
            # Default dimensions for content placeholder
            text_left = Inches(0.5)
            text_top = Inches(1.5)
            text_width = Inches(9.0)
            text_height = Inches(5.0)

            image_path = slide_data.get("image_path")
            if image_path and os.path.exists(image_path):
                # Adjust text box to make space for image on the right
                image_width = Inches(3.5)
                image_height = Inches(4.0)
                image_left = Inches(prs.slide_width - image_width - Inches(0.5)) # 0.5 inch right margin
                image_top = Inches(1.5)

                text_width = Inches(prs.slide_width - text_left - image_width - Inches(1.0)) # 1.0 for space between text and image
                
                slide.shapes.add_picture(image_path, image_left, image_top, width=image_width, height=image_height)

            content_placeholder.left = text_left
            content_placeholder.top = text_top
            content_placeholder.width = text_width
            content_placeholder.height = text_height

            tf = content_placeholder.text_frame
            tf.clear()
            tf.word_wrap = True
            tf.auto_size = MSO_AUTO_SIZE.SHAPE_TO_FIT_TEXT

            content = slide_data.get("content", "")
            if isinstance(content, list):
                for i, item in enumerate(content):
                    p = tf.add_paragraph()
                    p.text = item
                    p.level = 0 if i == 0 else 1
                    p.font.size = body_font_size
                    p.font.color.rgb = default_font_color
                    p.space_before = Pt(0)
                    p.space_after = Pt(0)
            else:
                p = tf.add_paragraph()
                p.text = content
                p.font.size = body_font_size
                p.font.color.rgb = default_font_color
                p.space_before = Pt(0)
                p.space_after = Pt(0)
        
        set_slide_background(slide)
        
    # --- "Questions?" Slide ---
    questions_slide_layout = prs.slide_layouts[5] 
    slide = prs.slides.add_slide(questions_slide_layout)

    title = slide.shapes.title
    title.text = "Questions?"
    title.text_frame.paragraphs[0].font.size = title_font_size
    title.text_frame.paragraphs[0].font.color.rgb = default_font_color

    set_slide_background(slide)

    # --- Save the presentation ---
    filename = f"{uuid.uuid4()}.pptx"
    output_path = f"storage/{filename}"
    prs.save(output_path)
    return output_path