from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
import json
import uuid
import os

def create_ppt_from_json(json_string: str):
    try:
        data = json.loads(json_string)
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON string provided to create_ppt_from_json: {json_string}")
        return None

    prs = Presentation()
    
    # --- Professional Design Elements (Dark Theme) ---
    background_color = RGBColor(12, 34, 56)
    default_font_color = RGBColor(255, 255, 255)
    title_font_size = Pt(44) 
    body_font_size = Pt(18)  

    def set_slide_background(slide):
        slide.background.fill.solid()
        slide.background.fill.fore_color.rgb = background_color
        
    # --- Title Slide ---
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_shape = slide.shapes.title
    title_text = data.get("presentation_title", "Presentation Title")
    title_shape.text = title_text
    title_shape.text_frame.paragraphs[0].font.size = title_font_size
    title_shape.text_frame.paragraphs[0].font.color.rgb = default_font_color
    
    if len(slide.placeholders) > 1:
        subtitle_shape = slide.placeholders[1]
        subtitle_shape.text = "Generated by Gemini"
        subtitle_shape.text_frame.paragraphs[0].font.size = Pt(24)
        subtitle_shape.text_frame.paragraphs[0].font.color.rgb = default_font_color
    
    set_slide_background(slide)

    # --- Content Slides ---
    for slide_data in data.get("slides", []):
        content_slide_layout = prs.slide_layouts[1] # Title and Content
        slide = prs.slides.add_slide(content_slide_layout)
        
        title_shape = slide.shapes.title
        title_shape.text = slide_data.get("title", "Slide Title")
        title_shape.text_frame.paragraphs[0].font.size = title_font_size
        title_shape.text_frame.paragraphs[0].font.color.rgb = default_font_color

        content_placeholder = None
        for shape in slide.placeholders:
            if shape.is_placeholder and shape.has_text_frame and shape.placeholder_format.idx == 1:
                content_placeholder = shape
                break
        
        if content_placeholder:
            tf = content_placeholder.text_frame
            tf.clear()
            tf.word_wrap = True
            
            content = slide_data.get("content", [])
            
            if isinstance(content, list) and content:
                for i, item in enumerate(content):
                    p = tf.add_paragraph()
                    p.text = str(item) # Ensure content is string
                    p.level = 0 if i == 0 else 1 # First item as level 0, subsequent as level 1 bullet
                    p.font.size = body_font_size
                    p.font.color.rgb = default_font_color
            elif isinstance(content, str) and content:
                p = tf.add_paragraph()
                p.text = content
                p.font.size = body_font_size
                p.font.color.rgb = default_font_color
            else:
                # Fallback for empty or invalid content
                p = tf.add_paragraph()
                p.text = "No specific content provided for this slide, but here is a placeholder."
                p.font.size = body_font_size
                p.font.color.rgb = default_font_color
        
        set_slide_background(slide)
        
    # --- "Questions?" Slide ---
    questions_slide_layout = prs.slide_layouts[5] 
    slide = prs.slides.add_slide(questions_slide_layout)

    title_shape = slide.shapes.title
    title_shape.text = "Questions & Discussion"
    title_shape.text_frame.paragraphs[0].font.size = title_font_size
    title_shape.text_frame.paragraphs[0].font.color.rgb = default_font_color

    set_slide_background(slide)

    # --- Save the presentation ---
    filename = f"{uuid.uuid4()}.pptx"
    output_dir = "storage"
    os.makedirs(output_dir, exist_ok=True) # Ensure storage directory exists
    output_path = os.path.join(output_dir, filename)
    prs.save(output_path)
    return output_path